jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:all
          name: Run YARN tests

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs: # declare what orbs we are going to use
  node: circleci/node@3.0.1 # the node orb provides common node-related configuration 

workflows:
  test-application:
    jobs:
      - install-node
      - test
        requires:
            - install-node